### ISSUE TITLE
Order of tests in administration test suite

### ISSUE THREAD

**Issue by oderwat** [SSPkrolik/nimongo#1]
Hi... I am checking out your mongodb module but struggle because if I run the `mongotest.nim` file I get an error on `listDatabases` because in an otherwise empty MongoDB server there is nothing to list and an error emerges from that. I reordered list and drop which makes more sense in my opinion. What do you think?

**Comment by SSPkrolik** [comment]
I think that's a badly written test. Tests must be independent, and order must not play any role here.

**Comment by SSPkrolik** [comment]
Fixed with slightly updated test suite
