### ISSUE TITLE
authentication failed

### ISSUE THREAD

**Issue by 15174400** [SSPkrolik/nimongo#68]
run nimongotest.  mongodb show error:
SCRAM-SHA-1 authentication failed for test2 on testdb from client 127.0.0.1:52419 ; AuthenticationFailed: SCRAM-SHA-1 authentication failed, storedKey mismatch

**Comment by JohnAD** [comment]
@15174400  Did you ever get this to work?

I see that Nim changed it's sha1 algorithm on Oct 9, 2018 and I wonder if this is broken now. I've tested multiple systems and can't get SCRAM-SHA-1 auth to work.
